on:
  push: 
    branches:
      - main

jobs:
  deploy:
    permissions: write-all
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: install dependencies
        run: npm ci
      - name: build
        run: npm run build
      - name: Debug Files
        run: ls
      - name: Deploy with gh-pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npx gh-pages -d dist -b actions -u "CaperAsDev <102335770+CaperAsDev@users.noreply.github.com.>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - uses: peterjgrainger/action-create-branch@v2.2.0
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     branch: 'first'
      # - uses: actions/upload-artifact@v4
      #   with:
      #     name: dist
      #     path: dist